packages:
  pkg.installed:
    - pkgs:
      - ack
      - apt-transport-https
      - binutils
      - bootstrap-vz
      - ca-certificates
      - curl
      - debootstrap
      - dnsutils
      - gcc
      - gnupg2
      - groff
      - htop
      - info
      - linux-headers-{{grains['osarch']}}
      - ltrace
      - make
      - net-tools
      - python-apt
      - software-properties-common
      - strace
      - sudo
      - texinfo
      - tig
      - tmux
